[package]
name = "mpd-notify"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
image = "0.25.9"
mpd_client = "1.4.1"
notify-rust = { version = "4.11.7", features = ["images"] }
tokio = { version = "1.48.0", features = ["full"] }
